feat(src/import): Add support for dotnet to cdk8s import.
cdk8s-team/cdk8s-cli pull request #2519
Opened 2024-07-26 14:19 UTC by ScottKane

Added support for calling `jsii-srcmak` with `csharp/dotnet` from `cdk8s import` (REGEX applied to convert names to PascalCase where possible)

2024-09-10 11:13 UTC, iliapolo commented
Looks like a we have another PR for this exact feature: https://github.com/cdk8s-team/cdk8s-cli/pull/2520.

@ScottKane How do you feel about reaching out to the author and deciding on the one PR we should be merging? :)

2024-09-10 11:15 UTC, iliapolo requested changes
Missing integ test. See https://github.com/cdk8s-team/cdk8s-cli/blob/2.x/test/integ/init.test.ts

2024-09-10 11:19 UTC, iliapolo commented
Ah ok this is just adding csharp to import and not as an init template. Still, we need a test for it then because its not covered by init tests.

2024-09-10 15:31 UTC, iliapolo commented
@ScottKane see https://github.com/cdk8s-team/cdk8s-cli/pull/2520#issuecomment-2341268022

2024-09-19 15:50 UTC, ScottKane commented
@iliapolo Integration test added and template added. I have also renamed everything to use the `csharp` convention

2024-09-19 16:09 UTC, ScottKane commented
also `jsii` seems to hard code target framework to `netcoreapp3.1` which isn't ideal but will solve that in the future

2025-01-03 12:06 UTC, ScottKane commented
@iliapolo is there anything else you want me to do here? afaik I addressed everything that was mentioned

2025-02-25 06:26 UTC, iliapolo approved these changes

2025-02-25 07:25 UTC, merged